OBJ = editor.o highlight.o row.o abuf.o terminal.o editorOp.o output.o input.o fileio.o find.o

all:
	gcc -g3 editor.c highlight.c row.c abuf.c terminal.c editorOp.c output.c input.c fileio.c find.c -o editor